import * as Main from "../../..";

export interface RequestQueryParameters extends Main.RequestQueryParameters {
	/** Your app’s [registered](https://dev.twitch.tv/docs/authentication/register-app) client ID. */
	client_id: string;
	/** Your app’s registered client secret. */
	client_secret: string;
	/** The code that the `/authorize` response returned in the `code` query parameter. */
	code: string;
	/** Your app’s registered redirect URI. */
	redirect_uri: string;
}

export type RequestParameters = RequestQueryParameters;

export interface ResponseBody {
	access_token: string;
	/** in seconds */
	expires_in: number;
	/**
	 * Refresh tokens are used to extend the lifetime of a given authorization.

	 * **NOTE**: You cannot refresh app access tokens.

	 * ### Can a refresh token become invalid?
	 * Yes, refresh tokens can become invalid. Refresh tokens, like access tokens, can become invalid if the user changes their password or disconnects your app. Most refresh tokens do not expire, but refresh tokens generated by a **Public** client type will expire **30 days** after they are generated, which will invalidate the refresh token. Most applications are set to the **Confidential** client type, of which the refresh tokens do not have an expiration time.
	 */
	refresh_token: string;
	// TODO: add Authorization.Scope here
	scope?: string[];
	token_type: "bearer";
}

export interface ResponseBodyError {
	/** HTTP error status code. */
	status: number;
	/**
	 * HTTP error message. Can be:
	 * Value|Reason
	 * -|-
	 * `missing client id`|`client_id` is empty string
	 * `invalid client`|`client_id` is not valid
	 * `missing client secret`|`client_secret` is empty string
	 * `invalid client secret`|`client_secret` is not valid
	 * `missing code`|`code` is empty string
	 * `Invalid authorization code`|`code` is not valid
	 * `missing redirect uri`|`redirect_uri` is empty string
	 * `invalid redirect uri`|`redirect_uri` is not valid
	 */
	message: string;
}

export function makeURL(params: RequestParameters) {
	const url = new Main.URL(params.apiPath ?? "token", Main.Options.idOAuth2Path);
	url.searchParams.appendMany({
		client_id: params.client_id,
		client_secret: params.client_secret,
		code: params.code,
		grant_type: "authorization_code",
		redirect_uri: params.redirect_uri,
	});
	return url;
}

export function makeFetchRequestInit(params: RequestParameters): RequestInit {
	return {
		method: "POST",
		headers: {
			"content-type": "application/x-www-form-urlencoded",
		},
		signal: params.signal,
	};
}

/**
 * ## [Authorization code grant flow](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#client-credentials-grant-flow)
 * Gets user access token and refresh token, this is meant for apps that use a server, can securely store a client secret, and can make server-to-server requests to the Twitch API.
 */
export async function fetch(params: RequestParameters): Promise<Main.Response<ResponseBody, ResponseBodyError>> {
	return global.fetch(makeURL(params).castToDefaultURL(), makeFetchRequestInit(params));
}