import * as Main from "../../..";
import * as GetUserAccessTokenWithAuthorizationCode from "./authorization_code";

export interface RequestQueryParameters {
	/** Your app’s [registered](https://dev.twitch.tv/docs/authentication/register-app) client ID. */
	client_id: string;
	/**
	 * Your app’s registered client secret.
	 * **NOTE**: This field is not required if your application’s client type was set to **public**.
	 */
	client_secret?: string;
	/** The refresh token issued to the client. */
	refresh_token: string;
}

export type RequestParameters = Main.RequestParameters & RequestQueryParameters;

export type ResponseBody = GetUserAccessTokenWithAuthorizationCode.ResponseBody;

export interface ResponseBodyError extends Main.ResponseBodyError {
	/**
	 * HTTP error message. Can be:
	 * Value|Reason
	 * -|-
	 * `missing client id`|`client_id` is empty string
	 * `invalid client`|`client_id` is not valid
	 * `missing client secret`|`client_secret` is empty string
	 * `invalid client secret`|`client_secret` is not valid
	 * `missing refresh token`|`refresh_token` is empty string
	 * `Invalid refresh token`|`refresh_token` is not valid
	 */
	message:
	| "missing client id"
	| "invalid client"
	| "missing client secret"
	| "invalid client secret"
	| "missing refresh token"
	| "Invalid refresh token";
}

export function prepareAxiosConfig(params: RequestParameters): Main.AxiosRequestConfig {
	return {
		baseURL: Main.Options.idOAuth2Path,
		url: "token",
		method: "POST",
		headers: {
			"content-type": "application/x-www-form-urlencoded",
		},
		params: {
			client_id: params.client_id,
			client_secret: params.client_secret,
			grant_type: "refresh_token",
			refresh_token: params.refresh_token,
		},
		...params.config,
	};
}

/**
 * ## [Refreshing user access token](https://dev.twitch.tv/docs/authentication/refresh-tokens/#how-to-use-a-refresh-token)
 * Refresh tokens are used to extend the lifetime of a given authorization.

 * **NOTE**: You cannot refresh app access tokens.

 * ### Can a refresh token become invalid?
 * Yes, refresh tokens can become invalid. Refresh tokens, like access tokens, can become invalid if the user changes their password or disconnects your app. Most refresh tokens do not expire, but refresh tokens generated by a **Public** client type will expire **30 days** after they are generated, which will invalidate the refresh token. Most applications are set to the **Confidential** client type, of which the refresh tokens do not have an expiration time.
 */
export async function axiosRequest(params: RequestParameters): Promise<Main.Response<ResponseBody, ResponseBodyError>> {
	return Main.axiosRequest(prepareAxiosConfig(params));
}